version: '3.9'

services:
  db:
    image: postgres:16
    container_name: test-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: test-django
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: 5432

volumes:
  pgdata:

