# django-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-rr7q*m83c_vbu51am^e(je*)xxb728h#+z91lg#ye_d_nv&iv)"

  DB_NAME: "mydb"
  DB_USER: "myuser"
  DB_PASSWORD: "1234"
  DB_HOST: "postgres-access" # 장고가 postgres를 접근할 때 사용할 Service Name
  DB_PORT: "5432"