# django-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: NodePort # 테스트를 위해 NodePort 사용
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80 # Service Port
      targetPort: 8000 # Container Port